import type { Alert, Device, Metric, Status } from '../types.js'

const now = () => new Date().toISOString(); const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v)); const round=(v:number,d=1)=>+v.toFixed(d)
const seedDevices=[['Edge-Router-01','192.168.1.1','Router','Core Room'],['Core-Switch-01','192.168.1.2','Switch','Core Room'],['App-Server-01','192.168.1.10','Server','Server Rack A'],['Database-01','192.168.1.11','Server','Server Rack B'],['Lab-PC-01','192.168.1.31','Computer','Computer Lab'],['Lab-PC-02','192.168.1.32','Computer','Computer Lab'],['West-AP-01','192.168.1.41','Access Point','West Wing'],['East-AP-01','192.168.1.42','Access Point','East Wing'],['Security-Cam-01','192.168.1.61','IoT Device','Main Entrance'],['IoT-Gateway-01','192.168.1.62','IoT Device','Floor 2'],['Print-Server-01','192.168.1.70','Server','Admin Office'],['Backup-Server-01','192.168.1.72','Server','Server Rack B']]
export class SimulationService {
  devices: Device[]=[]; metrics=new Map<number,Metric[]>(); alerts:Alert[]=[]; incident=0; private alertId=1;
  constructor(){ this.devices=seedDevices.map((d,i)=>{const latest=this.makeMetric(i+1, i===7?'warning':'online',new Date());return {id:i+1,name:d[0],address:d[1],type:d[2],location:d[3],status:i===7?'warning':'online',monitoringInterval:30,createdAt:now(),lastChecked:now(),latest}}); this.devices.forEach(d=>{const history:Metric[]=[];for(let i=143;i>=0;i--){const time=new Date(Date.now()-i*30*60*1000);history.push(this.makeMetric(d.id,d.status,time,i%41===0&&d.id===8));}this.metrics.set(d.id,history);d.latest=history.at(-1)!}); this.evaluateAll() }
  private makeMetric(id:number,status:Status,timestamp:Date,anomaly=false):Metric { const phase=(Date.now()/600000+id*1.7); const jitter=Math.sin(phase*2.3)*4+Math.cos(phase*1.17)*2; const troubled=status==='warning'||anomaly; const offline=status==='offline'; const latency=offline?0:clamp(34+jitter+(troubled?65:0),8,220); const loss=offline?100:clamp(.35+Math.max(0,jitter)/7+(troubled?5.4:0),0,25); const download=offline?0:clamp(87+Math.sin(phase)*15-(troubled?58:0),1,160); const upload=offline?0:clamp(31+Math.cos(phase*1.4)*6-(troubled?20:0),.2,70); return {timestamp:timestamp.toISOString(),latencyMs:round(latency),packetLossPercent:round(loss,2),downloadMbps:round(download),uploadMbps:round(upload),availabilityPercent:offline?0:round(100-loss*.12),errorCount:offline?5:troubled?2:0,responseTimeMs:round(latency+2)} }
  async check(id:number){ const device=this.getDevice(id); const status=this.incident===3&&id===8?'offline':this.incident===1&&id===8?'warning':device.status==='offline'?'offline':'online'; const metric=this.makeMetric(id,status,new Date(),this.incident===2&&id===8); device.status=status;device.latest=metric;device.lastChecked=metric.timestamp;const list=this.metrics.get(id)||[];list.push(metric);this.metrics.set(id,list.slice(-336));this.evaluate(device,metric);return metric }
  async tick(){await Promise.all(this.devices.map(d=>this.check(d.id)))}
  async runScenario(){this.incident=(this.incident+1)%5;await this.tick();return this.incident}
  getDevice(id:number){const device=this.devices.find(d=>d.id===id);if(!device)throw Object.assign(new Error('Device not found'),{status:404});return device}
  addDevice(input:Partial<Device>){const id=Math.max(...this.devices.map(d=>d.id),0)+1;const metric=this.makeMetric(id,'online',new Date());const device:Device={id,name:input.name||`Device-${id}`,address:input.address||'',type:input.type||'Computer',location:input.location||'Unspecified',status:'online',monitoringInterval:input.monitoringInterval||30,createdAt:now(),lastChecked:now(),latest:metric};this.devices.push(device);this.metrics.set(id,[metric]);return device}
  private evaluateAll(){this.devices.forEach(d=>this.evaluate(d,d.latest))}
  private evaluate(device:Device,metric:Metric){const checks:[string,number,number,string][]=[['latencyMs',metric.latencyMs,100,'High latency'],['packetLossPercent',metric.packetLossPercent,3,'High packet loss'],['downloadMbps',metric.downloadMbps,10,'Low bandwidth']];if(device.status==='offline')checks.push(['availabilityPercent',0,95,'Device offline']);for(const [metricName,value,threshold,label] of checks){const match=metricName==='downloadMbps'?value<threshold:value>threshold;if(match&&!this.alerts.some(a=>a.deviceId===device.id&&a.metric===metricName&&a.status==='active'))this.alerts.unshift({id:this.alertId++,deviceId:device.id,deviceName:device.name,metric:metricName,value:round(value),threshold,severity:device.status==='offline'||value>(threshold*1.5)?'critical':'warning',message:`${label}: ${device.name}`,status:'active',createdAt:metric.timestamp})}}
  updateAlert(id:number,status:'acknowledged'|'resolved'){const a=this.alerts.find(x=>x.id===id);if(!a)throw Object.assign(new Error('Alert not found'),{status:404});a.status=status;return a}
}
