import type { Metric } from '../types.js'

const round = (v: number, d = 2) => +v.toFixed(d)
const percentile = (sorted: number[], p: number) => { if (!sorted.length) return 0; const i=(sorted.length-1)*p; const lo=Math.floor(i), hi=Math.ceil(i); return round(sorted[lo]+(sorted[hi]-sorted[lo])*(i-lo)) }
export function statistics(records: Metric[], metric: keyof Metric, method: string) {
  const values=records.map(r=>Number(r[metric])).filter(Number.isFinite); const sorted=[...values].sort((a,b)=>a-b); const mean=values.reduce((a,b)=>a+b,0)/Math.max(values.length,1); const variance=values.reduce((a,b)=>a+(b-mean)**2,0)/Math.max(values.length,1); const standardDeviation=Math.sqrt(variance); const median=percentile(sorted,.5); const frequencies=new Map<number,number>(); values.forEach(v=>frequencies.set(v,(frequencies.get(v)||0)+1)); const mode=[...frequencies.entries()].sort((a,b)=>b[1]-a[1])[0];
  const q1=percentile(sorted,.25),q3=percentile(sorted,.75),iqr=q3-q1; const lower=q1-1.5*iqr,upper=q3+1.5*iqr;
  const anomalies=records.map(record=>{ const value=Number(record[metric]); const z=standardDeviation ? (value-mean)/standardDeviation : 0; const bad=method==='iqr' ? value<lower||value>upper : Math.abs(z)>3; return bad ? { timestamp:record.timestamp,value:round(value),expected:method==='iqr'?`${round(lower)} – ${round(upper)}`:`${round(mean-3*standardDeviation)} – ${round(mean+3*standardDeviation)}`,zScore:round(z),severity:Math.abs(z)>4?'critical':'warning' } : null }).filter(Boolean);
  const window=5; const movingAverage=values.map((_,i)=>round(values.slice(Math.max(0,i-window+1),i+1).reduce((a,b)=>a+b,0)/Math.min(i+1,window))); const first=values[0]||0,last=values.at(-1)||0;
  return { count:values.length,mean:round(mean),median,mode:mode&&mode[1]>1?mode[0]:null,min:round(sorted[0]||0),max:round(sorted.at(-1)||0),range:round((sorted.at(-1)||0)-(sorted[0]||0)),variance:round(variance),standardDeviation:round(standardDeviation),coefficientOfVariation:mean?round(standardDeviation/mean*100):0,percentiles:{P25:q1,P50:median,P75:q3,P90:percentile(sorted,.9),P95:percentile(sorted,.95),P99:percentile(sorted,.99)},trend:{direction:last>first?'increasing':last<first?'decreasing':'stable',percentChange:first?round((last-first)/Math.abs(first)*100):0,movingAverage},anomalies }
}
export function pearson(records: Metric[]) { const x=records.map(r=>r.latencyMs), y=records.map(r=>r.packetLossPercent); const mx=x.reduce((a,b)=>a+b,0)/x.length,my=y.reduce((a,b)=>a+b,0)/y.length; const top=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0); const bottom=Math.sqrt(x.reduce((s,v)=>s+(v-mx)**2,0)*y.reduce((s,v)=>s+(v-my)**2,0)); return bottom?round(top/bottom):0 }
